import { CampaignConfig, CampaignNodeConfig, Vec3 } from './campaignTypes';

const node = (
  id: string,
  label: string,
  position: Vec3,
  faction: string,
  baseControl: number,
  importance: number,
  subtitle?: string,
): CampaignNodeConfig => ({
  id,
  label,
  position,
  faction,
  baseControl,
  importance,
  subtitle,
});

export const chapter3dConfigs: Record<string, CampaignConfig> = {
  'timur-legacy': {
    chapterId: 'timur-legacy',
    chapterTitle: "The Iron Emir - Timur's Legacy",
    terrain: { profile: 'steppe', size: [24, 16], heightScale: 0.9, fogDensity: 0.25 },
    palette: {
      terrain: '#7c5b3b',
      terrainAccent: '#d97706',
      fog: '#b45309',
      ambient: '#312e1f',
      keyLight: '#f59e0b',
      pulse: '#fbbf24',
    },
    factions: {
      timurid: '#fbbf24',
      ottoman: '#ef4444',
      mamluk: '#22c55e',
      ming: '#10b981',
      warlords: '#9ca3af',
    },
    nodes: [
      node('samarkand', 'Samarkand', [0, 0.25, 0], 'timurid', 0.72, 1, 'Capital'),
      node('herat', 'Herat', [-3.2, 0.22, -1.8], 'timurid', 0.64, 0.65),
      node('tabriz', 'Tabriz', [-5.2, 0.3, 0.4], 'ottoman', 0.52, 0.7),
      node('delhi', 'Delhi', [2.2, 0.22, -3.3], 'timurid', 0.48, 0.78),
      node('damascus', 'Damascus', [-6.8, 0.15, -2.2], 'mamluk', 0.42, 0.55),
      node('ankara', 'Ankara', [-7.8, 0.3, 1.8], 'ottoman', 0.44, 0.84),
      node('beijing', 'Beijing', [7.8, 0.28, 2.2], 'ming', 0.38, 0.9),
    ],
    fronts: [
      { id: 'silk-west', from: 'samarkand', to: 'tabriz', baseTension: 0.46, label: 'Silk Road West' },
      { id: 'silk-south', from: 'samarkand', to: 'delhi', baseTension: 0.42, label: 'Indus Axis' },
      { id: 'syria-route', from: 'tabriz', to: 'damascus', baseTension: 0.56, label: 'Levant Pressure' },
      { id: 'ankara-siege', from: 'samarkand', to: 'ankara', baseTension: 0.62, label: 'Ankara Corridor' },
      { id: 'china-march', from: 'samarkand', to: 'beijing', baseTension: 0.52, label: 'Ming Expedition' },
      { id: 'anatolia-levant', from: 'ankara', to: 'damascus', baseTension: 0.4, label: 'Anatolian Relief' },
    ],
    units: [
      { id: 'timur-guard', faction: 'timurid', color: '#fbbf24', route: ['samarkand', 'ankara', 'damascus'], speed: 0.95, size: 0.24 },
      { id: 'silk-caravan', faction: 'timurid', color: '#f59e0b', route: ['samarkand', 'herat', 'delhi'], speed: 0.68, size: 0.19 },
      { id: 'ottoman-line', faction: 'ottoman', color: '#ef4444', route: ['ankara', 'tabriz', 'damascus'], speed: 0.7, size: 0.21 },
      { id: 'ming-garrison', faction: 'ming', color: '#10b981', route: ['beijing', 'samarkand'], speed: 0.58, size: 0.2 },
    ],
    branches: [
      { id: 'immortal-emir', title: 'Immortal Emir', color: '#fbbf24', description: 'Timur extends his reign.', baseScore: 0.45, statWeights: { strength: 0.36, diplomacy: -0.08 } },
      { id: 'unified-succession', title: 'Unified Succession', color: '#60a5fa', description: 'Stable Timurid institutions.', baseScore: 0.38, statWeights: { diplomacy: 0.4, freedom: 0.12 } },
      { id: 'western-campaign', title: 'Western Campaign', color: '#dc2626', description: 'Europe-facing invasion arc.', baseScore: 0.35, statWeights: { chaos: 0.34, strength: 0.22 } },
    ],
    microScenes: [
      {
        id: 'ankara-siege',
        title: 'Siege of Ankara (1402)',
        description: 'War elephants and arrow volleys break Anatolian defenses.',
        triggerScenarioIds: ['ankara-strategy', 'direct-charge', 'cut-water'],
        kind: 'siege',
        focusNodeIds: ['ankara', 'samarkand'],
        primaryMetricLabel: 'Fortification Integrity',
        secondaryMetricLabel: 'Timurid Morale',
      },
    ],
    educationalNotes: [
      'Samarkand functions as the strategic heart of Timurid command and logistics.',
      'Silk Road arcs brighten under diplomatic-heavy choices, signaling stable trade corridors.',
      'Ankara pressure reflects whether Timur secures Anatolia or overextends westward.',
      'Beijing reach indicates the feasibility of a sustained eastward conquest.',
    ],
  },

  'us-independence': {
    chapterId: 'us-independence',
    chapterTitle: 'U.S. Independence Campaign',
    terrain: { profile: 'coastal', size: [22, 14], heightScale: 0.65, fogDensity: 0.22 },
    palette: {
      terrain: '#334155',
      terrainAccent: '#1d4ed8',
      fog: '#1e3a8a',
      ambient: '#0f172a',
      keyLight: '#60a5fa',
      pulse: '#93c5fd',
    },
    factions: {
      patriots: '#3b82f6',
      british: '#ef4444',
      french: '#38bdf8',
      loyalists: '#f59e0b',
    },
    nodes: [
      node('boston', 'Boston', [-4.8, 0.22, 3.2], 'patriots', 0.56, 0.74),
      node('new-york', 'New York', [-3.8, 0.2, 2.1], 'british', 0.48, 0.9),
      node('philadelphia', 'Philadelphia', [-3.2, 0.22, 1.3], 'patriots', 0.62, 0.95, 'Congress'),
      node('chesapeake', 'Chesapeake', [-2.3, 0.14, -0.1], 'french', 0.44, 0.72),
      node('valley-forge', 'Valley Forge', [-3.5, 0.34, 1], 'patriots', 0.54, 0.64),
      node('charleston', 'Charleston', [-0.2, 0.1, -3.7], 'british', 0.42, 0.58),
      node('yorktown', 'Yorktown', [-2.1, 0.14, -1.1], 'patriots', 0.52, 0.82),
    ],
    fronts: [
      { id: 'north-corridor', from: 'boston', to: 'new-york', baseTension: 0.52, label: 'Northern Front' },
      { id: 'congress-line', from: 'new-york', to: 'philadelphia', baseTension: 0.48, label: 'Congress Corridor' },
      { id: 'forge-axis', from: 'philadelphia', to: 'valley-forge', baseTension: 0.44, label: 'Winter Camp Axis' },
      { id: 'coastal-south', from: 'chesapeake', to: 'charleston', baseTension: 0.4, label: 'Coastal Campaign' },
      { id: 'yorktown-trap', from: 'chesapeake', to: 'yorktown', baseTension: 0.63, label: 'Yorktown Closure' },
      { id: 'retreat-fog', from: 'new-york', to: 'yorktown', baseTension: 0.46, label: 'Retreat and Pursuit' },
    ],
    units: [
      { id: 'continental-army', faction: 'patriots', color: '#3b82f6', route: ['valley-forge', 'philadelphia', 'yorktown'], speed: 0.74, size: 0.2 },
      { id: 'redcoats', faction: 'british', color: '#ef4444', route: ['new-york', 'chesapeake', 'yorktown'], speed: 0.82, size: 0.22 },
      { id: 'french-fleet', faction: 'french', color: '#38bdf8', route: ['chesapeake', 'charleston', 'chesapeake'], speed: 0.9, size: 0.2 },
      { id: 'militia', faction: 'loyalists', color: '#f59e0b', route: ['boston', 'philadelphia', 'charleston'], speed: 0.62, size: 0.16 },
    ],
    branches: [
      { id: 'british-victory', title: 'British Victory', color: '#ef4444', description: 'Colonial rebellion collapses.', baseScore: 0.32, statWeights: { strength: 0.2, diplomacy: -0.3, freedom: -0.25 } },
      { id: 'french-america', title: 'French America', color: '#38bdf8', description: 'French patronage dominates.', baseScore: 0.31, statWeights: { diplomacy: 0.42, strength: -0.08 } },
      { id: 'confederated-states', title: 'Confederated States', color: '#f59e0b', description: 'Loose federation persists.', baseScore: 0.29, statWeights: { freedom: 0.25, chaos: 0.3 } },
    ],
    microScenes: [
      {
        id: 'yorktown-artillery',
        title: 'Yorktown Siege Batteries',
        description: 'Continental artillery suppresses British trenches and redoubts.',
        triggerScenarioIds: ['yorktown', 'join', 'report'],
        kind: 'siege',
        focusNodeIds: ['yorktown', 'chesapeake'],
        primaryMetricLabel: 'Battery Accuracy',
        secondaryMetricLabel: 'British Cohesion',
      },
      {
        id: 'chesapeake-naval',
        title: 'Chesapeake Naval Engagement',
        description: 'French and British fleets duel under shifting wind vectors.',
        triggerScenarioIds: ['chesapeake', 'fight', 'navy-blockade'],
        kind: 'naval',
        focusNodeIds: ['chesapeake'],
        primaryMetricLabel: 'Cannon Exchange',
        secondaryMetricLabel: 'Wind Advantage',
      },
      {
        id: 'declaration-signing',
        title: 'Declaration Signing Chamber',
        description: 'Delegates debate language and sovereign legitimacy in Congress.',
        triggerScenarioIds: ['continental-congress', 'demand-rights'],
        kind: 'ceremony',
        focusNodeIds: ['philadelphia'],
        primaryMetricLabel: 'Delegate Alignment',
        secondaryMetricLabel: 'Public Resolve',
      },
    ],
    educationalNotes: [
      'Appalachian variation is represented as ridged inland elevation behind the coastal nodes.',
      'Valley Forge scenarios increase snow/fog pressure in the northern corridor.',
      'Chesapeake naval pressure drives the Yorktown closure probability in branch rails.',
      'Philadelphia overlays explain declaration framing and legal stakes.',
    ],
  },

  'french-revolution': {
    chapterId: 'french-revolution',
    chapterTitle: 'French Revolution',
    terrain: { profile: 'river', size: [20, 14], heightScale: 0.58, fogDensity: 0.24 },
    palette: {
      terrain: '#4c1d1d',
      terrainAccent: '#f97316',
      fog: '#7f1d1d',
      ambient: '#1f1212',
      keyLight: '#fb923c',
      pulse: '#ef4444',
    },
    factions: {
      royalists: '#facc15',
      jacobins: '#ef4444',
      girondins: '#3b82f6',
      commune: '#f97316',
      army: '#9ca3af',
    },
    nodes: [
      node('paris', 'Paris', [0.2, 0.2, 1.3], 'jacobins', 0.52, 1, 'Seine Core'),
      node('versailles', 'Versailles', [-0.2, 0.2, 1], 'royalists', 0.44, 0.72),
      node('bastille', 'Bastille', [0.4, 0.2, 1.5], 'jacobins', 0.5, 0.88),
      node('lyon', 'Lyon', [0.8, 0.16, -0.2], 'girondins', 0.47, 0.6),
      node('vendee', 'Vendee', [-1.9, 0.16, -0.5], 'royalists', 0.42, 0.58),
      node('toulon', 'Toulon', [1.8, 0.08, -2.4], 'army', 0.46, 0.64),
      node('valmy', 'Valmy', [1.6, 0.2, 2.5], 'jacobins', 0.48, 0.78),
    ],
    fronts: [
      { id: 'seine-pressure', from: 'paris', to: 'versailles', baseTension: 0.58, label: 'Seine Political Axis' },
      { id: 'bastille-march', from: 'paris', to: 'bastille', baseTension: 0.6, label: 'Crowd Surge' },
      { id: 'lyon-revolt', from: 'paris', to: 'lyon', baseTension: 0.44, label: 'Federal Resistance' },
      { id: 'vendee-war', from: 'paris', to: 'vendee', baseTension: 0.5, label: 'Vendee Uprising' },
      { id: 'mediterranean', from: 'lyon', to: 'toulon', baseTension: 0.42, label: 'Southern Theater' },
      { id: 'valmy-defense', from: 'paris', to: 'valmy', baseTension: 0.53, label: 'Border Defense' },
    ],
    units: [
      { id: 'national-guard', faction: 'jacobins', color: '#ef4444', route: ['paris', 'bastille', 'versailles'], speed: 0.76, size: 0.2 },
      { id: 'royalist-column', faction: 'royalists', color: '#facc15', route: ['versailles', 'vendee', 'paris'], speed: 0.68, size: 0.21 },
      { id: 'republican-army', faction: 'army', color: '#9ca3af', route: ['valmy', 'paris', 'lyon'], speed: 0.73, size: 0.2 },
      { id: 'girondin-network', faction: 'girondins', color: '#3b82f6', route: ['lyon', 'toulon', 'paris'], speed: 0.62, size: 0.16 },
    ],
    branches: [
      { id: 'constitutional-monarchy', title: 'Constitutional Monarchy', color: '#60a5fa', description: 'Reform without terror.', baseScore: 0.35, statWeights: { diplomacy: 0.36, chaos: -0.24 } },
      { id: 'robespierre-eternal', title: 'Robespierre Eternal', color: '#dc2626', description: 'Radical terror state.', baseScore: 0.34, statWeights: { chaos: 0.42, strength: 0.12 } },
      { id: 'girondist-victory', title: 'Girondist Victory', color: '#34d399', description: 'Moderate republican federalism.', baseScore: 0.3, statWeights: { freedom: 0.3, diplomacy: 0.2 } },
    ],
    microScenes: [
      {
        id: 'bastille-storm',
        title: 'Storming the Bastille',
        description: 'Crowd waves, cannon smoke, and drawbridge collapse pressure.',
        triggerScenarioIds: ['estates-general', 'storm', 'bastille'],
        kind: 'uprising',
        focusNodeIds: ['bastille', 'paris'],
        primaryMetricLabel: 'Crowd Momentum',
        secondaryMetricLabel: 'Garrison Stability',
      },
      {
        id: 'terror-square',
        title: 'Reign of Terror Square',
        description: 'Public executions alter city morale and political fear.',
        triggerScenarioIds: ['reign-of-terror', 'robespierre'],
        kind: 'political',
        focusNodeIds: ['paris'],
        primaryMetricLabel: 'Public Tension',
        secondaryMetricLabel: 'Committee Control',
      },
    ],
    educationalNotes: [
      'The Seine axis is represented as a low-elevation corridor through Paris.',
      'Early scenes favor warm lighting; terror-heavy paths shift branch bloom toward red.',
      'Bastille pressure displays crowd-size and morale changes from each civic choice.',
      'Valmy node overlays highlight external coalition pressure on revolutionary politics.',
    ],
  },

  'russian-empire': {
    chapterId: 'russian-empire',
    chapterTitle: 'Russian Empire & Central Asia',
    terrain: { profile: 'mountain', size: [28, 16], heightScale: 1.1, fogDensity: 0.33 },
    palette: {
      terrain: '#1f2937',
      terrainAccent: '#2563eb',
      fog: '#1e40af',
      ambient: '#0b1020',
      keyLight: '#93c5fd',
      pulse: '#22d3ee',
    },
    factions: {
      imperial: '#1d4ed8',
      khanates: '#14b8a6',
      british: '#ef4444',
      ottoman: '#f97316',
      persian: '#a855f7',
    },
    nodes: [
      node('st-petersburg', 'St. Petersburg', [-6, 0.36, 3.6], 'imperial', 0.68, 0.9),
      node('moscow', 'Moscow', [-4.2, 0.32, 1.4], 'imperial', 0.66, 0.88),
      node('omsk', 'Omsk', [-0.4, 0.28, 1], 'imperial', 0.54, 0.62),
      node('tashkent', 'Tashkent', [1.8, 0.2, -0.8], 'khanates', 0.46, 0.72),
      node('kabul', 'Kabul', [3.8, 0.16, -2.4], 'british', 0.42, 0.66),
      node('tbilisi', 'Tbilisi', [-1.1, 0.24, -1.8], 'ottoman', 0.45, 0.58),
      node('vladivostok', 'Vladivostok', [6.4, 0.32, 2.2], 'imperial', 0.52, 0.74),
    ],
    fronts: [
      { id: 'trans-siberian', from: 'st-petersburg', to: 'vladivostok', baseTension: 0.5, label: 'Trans-Siberian Corridor' },
      { id: 'caucasus-line', from: 'moscow', to: 'tbilisi', baseTension: 0.54, label: 'Caucasus Pressure' },
      { id: 'steppe-axis', from: 'omsk', to: 'tashkent', baseTension: 0.51, label: 'Central Asian Expansion' },
      { id: 'afghan-frontier', from: 'tashkent', to: 'kabul', baseTension: 0.63, label: 'Afghan Frontier' },
      { id: 'great-game', from: 'kabul', to: 'tbilisi', baseTension: 0.44, label: 'Great Game Link' },
      { id: 'eastern-pivot', from: 'omsk', to: 'vladivostok', baseTension: 0.4, label: 'Asian Pivot' },
    ],
    units: [
      { id: 'imperial-rail-corps', faction: 'imperial', color: '#1d4ed8', route: ['st-petersburg', 'moscow', 'omsk', 'vladivostok'], speed: 0.72, size: 0.2 },
      { id: 'cossack-column', faction: 'imperial', color: '#60a5fa', route: ['moscow', 'tbilisi', 'tashkent'], speed: 0.84, size: 0.22 },
      { id: 'khanate-riders', faction: 'khanates', color: '#14b8a6', route: ['tashkent', 'kabul', 'tbilisi'], speed: 0.77, size: 0.19 },
      { id: 'british-expedition', faction: 'british', color: '#ef4444', route: ['kabul', 'tashkent'], speed: 0.66, size: 0.2 },
    ],
    branches: [
      { id: 'constitutional-russia', title: 'Constitutional Empire', color: '#34d399', description: 'Reformist imperial path.', baseScore: 0.34, statWeights: { diplomacy: 0.36, freedom: 0.22 } },
      { id: 'traditionalist-russia', title: 'Traditionalist Empire', color: '#f97316', description: 'Autocratic continuity.', baseScore: 0.33, statWeights: { strength: 0.32, freedom: -0.25 } },
      { id: 'sino-russian', title: 'Asian Pivot', color: '#22d3ee', description: 'Eurasian eastern realignment.', baseScore: 0.31, statWeights: { diplomacy: 0.16, strength: 0.24 } },
    ],
    microScenes: [
      {
        id: 'geok-tepe',
        title: 'Siege of Geok-Tepe',
        description: 'Artillery breach progression and trench push timing.',
        triggerScenarioIds: ['afghan-frontier', 'decembrist-revolt', 'crush'],
        kind: 'siege',
        focusNodeIds: ['tashkent', 'kabul'],
        primaryMetricLabel: 'Breach Progress',
        secondaryMetricLabel: 'Defender Cohesion',
      },
    ],
    educationalNotes: [
      'Northern nodes use colder illumination while southern fronts shift warmer under pressure.',
      'Trans-Siberian tension indicates logistical strain from west-east balancing.',
      'Great Game corridors model Anglo-Russian rivalry in Central Asia.',
      'Caucasus relief emphasizes mountain friction and imperial overstretch.',
    ],
  },

  'lincoln-era': {
    chapterId: 'lincoln-era',
    chapterTitle: 'Life of Abraham Lincoln',
    terrain: { profile: 'battlefield', size: [26, 16], heightScale: 0.7, fogDensity: 0.36 },
    palette: {
      terrain: '#374151',
      terrainAccent: '#1d4ed8',
      fog: '#475569',
      ambient: '#111827',
      keyLight: '#93c5fd',
      pulse: '#f59e0b',
    },
    factions: {
      union: '#2563eb',
      confederacy: '#9ca3af',
      border: '#f59e0b',
      militia: '#14b8a6',
    },
    nodes: [
      node('washington', 'Washington D.C.', [2.2, 0.24, 1.75], 'union', 0.68, 0.9),
      node('richmond', 'Richmond', [2, 0.2, 0.72], 'confederacy', 0.45, 0.82),
      node('gettysburg', 'Gettysburg', [2.15, 0.26, 2.35], 'union', 0.52, 0.88),
      node('vicksburg', 'Vicksburg', [-3.9, 0.16, -2.9], 'union', 0.5, 0.72),
      node('atlanta', 'Atlanta', [-1.05, 0.16, -1.95], 'confederacy', 0.44, 0.76),
      node('fort-sumter', 'Fort Sumter', [0.95, 0.1, -2.62], 'confederacy', 0.42, 0.62),
      node('appomattox', 'Appomattox', [1.45, 0.2, 0.62], 'union', 0.48, 0.7),
    ],
    fronts: [
      { id: 'eastern-theater', from: 'washington', to: 'richmond', baseTension: 0.62, label: 'Eastern Theater' },
      { id: 'gettysburg-line', from: 'washington', to: 'gettysburg', baseTension: 0.56, label: 'Pennsylvania Arc' },
      { id: 'western-theater', from: 'vicksburg', to: 'atlanta', baseTension: 0.53, label: 'Western Theater' },
      { id: 'mississippi-campaign', from: 'vicksburg', to: 'fort-sumter', baseTension: 0.44, label: 'Mississippi Campaign' },
      { id: 'appomattox-collapse', from: 'richmond', to: 'appomattox', baseTension: 0.6, label: 'Final Collapse' },
      { id: 'coastal-blockade', from: 'fort-sumter', to: 'washington', baseTension: 0.41, label: 'Naval Blockade' },
    ],
    units: [
      { id: 'union-army', faction: 'union', color: '#2563eb', route: ['washington', 'gettysburg', 'richmond', 'appomattox'], speed: 0.74, size: 0.22 },
      { id: 'confederate-army', faction: 'confederacy', color: '#9ca3af', route: ['richmond', 'gettysburg', 'atlanta'], speed: 0.71, size: 0.22 },
      { id: 'western-corps', faction: 'union', color: '#60a5fa', route: ['vicksburg', 'atlanta', 'appomattox'], speed: 0.69, size: 0.19 },
      { id: 'freed-militia', faction: 'militia', color: '#14b8a6', route: ['fort-sumter', 'vicksburg', 'washington'], speed: 0.62, size: 0.16 },
    ],
    branches: [
      { id: 'lincoln-survives', title: 'Lincoln Survives', color: '#3b82f6', description: 'Reconstruction under Lincoln.', baseScore: 0.36, statWeights: { diplomacy: 0.32, freedom: 0.25 } },
      { id: 'peaceful-abolition', title: 'Peaceful Abolition', color: '#22c55e', description: 'No full civil rupture.', baseScore: 0.3, statWeights: { diplomacy: 0.34, strength: -0.14 } },
      { id: 'confederacy-wins', title: 'Two Nations', color: '#ef4444', description: 'Confederate strategic success.', baseScore: 0.34, statWeights: { chaos: 0.4, strength: 0.12 } },
    ],
    microScenes: [
      {
        id: 'gettysburg-charge',
        title: "Pickett's Charge",
        description: 'Formation blocks cross open field under artillery fire.',
        triggerScenarioIds: ['gettysburg', 'hold-line', 'retreat'],
        kind: 'trench',
        focusNodeIds: ['gettysburg', 'richmond'],
        primaryMetricLabel: 'Casualty Pressure',
        secondaryMetricLabel: 'Union Morale',
      },
    ],
    educationalNotes: [
      'The glowing Mason-Dixon front reflects control volatility between Union and Confederacy.',
      'Mississippi corridor pressure mirrors supply severance and western campaign gains.',
      'Gettysburg micro-scene tracks momentum swings during Pickett-style assaults.',
      'Appomattox path highlights end-state cohesion collapse.',
    ],
  },

  'lenin-revolution': {
    chapterId: 'lenin-revolution',
    chapterTitle: 'Life of Lenin',
    terrain: { profile: 'industrial', size: [21, 14], heightScale: 0.68, fogDensity: 0.38 },
    palette: {
      terrain: '#2f2f38',
      terrainAccent: '#b91c1c',
      fog: '#4b5563',
      ambient: '#111827',
      keyLight: '#ef4444',
      pulse: '#dc2626',
    },
    factions: {
      bolshevik: '#dc2626',
      menshevik: '#f472b6',
      white: '#f3f4f6',
      intervention: '#22c55e',
      anarchist: '#111827',
    },
    nodes: [
      node('petrograd', 'Petrograd', [-3.8, 0.24, 2.1], 'bolshevik', 0.58, 0.92),
      node('moscow', 'Moscow', [-2.6, 0.22, 0.4], 'bolshevik', 0.6, 0.88),
      node('kiev', 'Kiev', [-3.6, 0.2, -1.8], 'menshevik', 0.44, 0.68),
      node('omsk', 'Omsk', [0.6, 0.22, 1.2], 'white', 0.46, 0.74),
      node('kronstadt', 'Kronstadt', [-4.5, 0.2, 2.9], 'anarchist', 0.4, 0.58),
      node('baku', 'Baku', [1.8, 0.18, -2.2], 'intervention', 0.43, 0.66),
    ],
    fronts: [
      { id: 'palace-axis', from: 'petrograd', to: 'moscow', baseTension: 0.55, label: 'Capital Axis' },
      { id: 'white-encircle', from: 'omsk', to: 'moscow', baseTension: 0.61, label: 'White Encirclement' },
      { id: 'kiev-push', from: 'kiev', to: 'moscow', baseTension: 0.48, label: 'Southwest Front' },
      { id: 'foreign-corridor', from: 'baku', to: 'omsk', baseTension: 0.5, label: 'Foreign Intervention' },
      { id: 'naval-revolt', from: 'kronstadt', to: 'petrograd', baseTension: 0.54, label: 'Naval Revolt' },
      { id: 'caucasus-fuel', from: 'baku', to: 'moscow', baseTension: 0.47, label: 'Fuel Security' },
    ],
    units: [
      { id: 'red-guards', faction: 'bolshevik', color: '#dc2626', route: ['petrograd', 'moscow', 'kiev'], speed: 0.78, size: 0.21 },
      { id: 'white-columns', faction: 'white', color: '#f3f4f6', route: ['omsk', 'moscow', 'petrograd'], speed: 0.7, size: 0.2 },
      { id: 'menshevik-cadres', faction: 'menshevik', color: '#f472b6', route: ['kiev', 'moscow'], speed: 0.63, size: 0.16 },
      { id: 'intervention-force', faction: 'intervention', color: '#22c55e', route: ['baku', 'omsk', 'kiev'], speed: 0.66, size: 0.19 },
    ],
    branches: [
      { id: 'menshevik-victory', title: 'Menshevik Path', color: '#f472b6', description: 'Parliamentary socialist path.', baseScore: 0.34, statWeights: { diplomacy: 0.38, freedom: 0.2 } },
      { id: 'trotsky-victory', title: 'White Victory / Global War', color: '#e5e7eb', description: 'Escalatory militarized trajectory.', baseScore: 0.33, statWeights: { chaos: 0.34, strength: 0.22 } },
      { id: 'lenin-lives', title: 'Lenin Lives', color: '#b91c1c', description: 'NEP continuity and centralized rule.', baseScore: 0.33, statWeights: { strength: 0.3, diplomacy: -0.06 } },
    ],
    microScenes: [
      {
        id: 'winter-palace',
        title: 'Storming the Winter Palace',
        description: 'Red Guards breach gates while Aurora signals uprising timing.',
        triggerScenarioIds: ['october-revolution', 'seize-power'],
        kind: 'uprising',
        focusNodeIds: ['petrograd'],
        primaryMetricLabel: 'Palace Breach',
        secondaryMetricLabel: 'Guard Loyalty',
      },
    ],
    educationalNotes: [
      'Industrial haze thickens as chaos and strength increase in urban centers.',
      'Omsk routes visualize White Army encirclement pressure around Moscow.',
      'Kronstadt line captures the naval mutiny risk to Bolshevik legitimacy.',
      'Winter Palace micro-scene highlights tactical timing and command cohesion.',
    ],
  },

  'hitler-rise': {
    chapterId: 'hitler-rise',
    chapterTitle: 'Life of Hitler',
    terrain: { profile: 'urban', size: [20, 13], heightScale: 0.52, fogDensity: 0.34 },
    palette: {
      terrain: '#1f2937',
      terrainAccent: '#b91c1c',
      fog: '#334155',
      ambient: '#0b0f18',
      keyLight: '#fca5a5',
      pulse: '#dc2626',
    },
    factions: {
      nazi: '#7f1d1d',
      weimar: '#facc15',
      kpd: '#dc2626',
      military: '#6b7280',
      resistance: '#f8fafc',
    },
    nodes: [
      node('berlin', 'Berlin', [0.8, 0.24, 1.2], 'weimar', 0.46, 0.94),
      node('munich', 'Munich', [-1.2, 0.22, -1], 'nazi', 0.52, 0.9),
      node('vienna', 'Vienna', [-2.9, 0.2, -0.2], 'weimar', 0.41, 0.68),
      node('nuremberg', 'Nuremberg', [-0.2, 0.22, -0.2], 'nazi', 0.5, 0.74),
      node('berchtesgaden', 'Berchtesgaden', [-1.8, 0.18, -2.3], 'nazi', 0.44, 0.62),
      node('wolfs-lair', "Wolf's Lair", [2.6, 0.2, -0.8], 'military', 0.42, 0.66),
    ],
    fronts: [
      { id: 'sa-streets', from: 'munich', to: 'berlin', baseTension: 0.58, label: 'SA Street Violence' },
      { id: 'rally-route', from: 'nuremberg', to: 'berlin', baseTension: 0.52, label: 'Rally Network' },
      { id: 'kpd-resistance', from: 'berlin', to: 'vienna', baseTension: 0.46, label: 'Left Opposition' },
      { id: 'mountain-command', from: 'berchtesgaden', to: 'munich', baseTension: 0.5, label: 'Mountain HQ' },
      { id: 'valkyrie-axis', from: 'wolfs-lair', to: 'berlin', baseTension: 0.57, label: 'Valkyrie Risk' },
      { id: 'weimar-fragment', from: 'vienna', to: 'nuremberg', baseTension: 0.44, label: 'Weimar Fragmentation' },
    ],
    units: [
      { id: 'sa-columns', faction: 'nazi', color: '#7f1d1d', route: ['munich', 'nuremberg', 'berlin'], speed: 0.74, size: 0.2 },
      { id: 'weimar-police', faction: 'weimar', color: '#facc15', route: ['berlin', 'munich'], speed: 0.62, size: 0.18 },
      { id: 'resistance-cells', faction: 'resistance', color: '#f8fafc', route: ['berlin', 'wolfs-lair', 'berlin'], speed: 0.68, size: 0.16 },
      { id: 'military-command', faction: 'military', color: '#6b7280', route: ['wolfs-lair', 'berchtesgaden', 'berlin'], speed: 0.66, size: 0.19 },
    ],
    branches: [
      { id: 'art-school-timeline', title: 'The Artist', color: '#f59e0b', description: 'Peaceful artistic divergence.', baseScore: 0.3, statWeights: { freedom: 0.38, chaos: -0.2 } },
      { id: 'beer-hall-success', title: 'Beer Hall Success', color: '#b91c1c', description: 'Early putsch escalation.', baseScore: 0.35, statWeights: { chaos: 0.4, strength: 0.12 } },
      { id: 'assassination-success', title: 'Assassination Success', color: '#d1d5db', description: 'Valkyrie succeeds.', baseScore: 0.35, statWeights: { diplomacy: 0.24, strength: -0.08 } },
    ],
    microScenes: [
      {
        id: 'beer-hall-putsch',
        title: 'Beer Hall Putsch Street Clash',
        description: 'March columns meet police barricades with rapid morale collapse.',
        triggerScenarioIds: ['beer-hall', 'march', 'capture-leaders'],
        kind: 'urban',
        focusNodeIds: ['munich', 'nuremberg'],
        primaryMetricLabel: 'Barricade Pressure',
        secondaryMetricLabel: 'Crowd Scatter',
      },
    ],
    educationalNotes: [
      'Political corridors show influence spread rather than conventional military fronts.',
      'Wet-street noir palette intensifies as chaos grows.',
      'Munich overlays explain why the failed putsch still altered long-term strategy.',
      'Valkyrie lines represent military-resistance communication reliability.',
    ],
  },

  'world-war-1': {
    chapterId: 'world-war-1',
    chapterTitle: 'World War I',
    terrain: { profile: 'battlefield', size: [23, 14], heightScale: 0.75, fogDensity: 0.32 },
    palette: {
      terrain: '#3f3f46',
      terrainAccent: '#a16207',
      fog: '#52525b',
      ambient: '#111827',
      keyLight: '#f59e0b',
      pulse: '#f97316',
    },
    factions: {
      entente: '#2563eb',
      central: '#dc2626',
      ottoman: '#f97316',
      neutral: '#9ca3af',
    },
    nodes: [
      node('sarajevo', 'Sarajevo', [-2, 0.2, 0], 'neutral', 0.4, 0.7),
      node('vienna', 'Vienna', [-1.2, 0.22, 1.4], 'central', 0.48, 0.8),
      node('berlin', 'Berlin', [-0.2, 0.24, 2.3], 'central', 0.56, 0.9),
      node('paris', 'Paris', [-2.8, 0.2, 2], 'entente', 0.52, 0.88),
      node('london', 'London', [-4.4, 0.16, 2.6], 'entente', 0.6, 0.82),
      node('st-petersburg', 'St. Petersburg', [1.8, 0.24, 2.4], 'entente', 0.48, 0.74),
      node('constantinople', 'Constantinople', [1.3, 0.18, -1.8], 'ottoman', 0.44, 0.66),
    ],
    fronts: [
      { id: 'western-front', from: 'berlin', to: 'paris', baseTension: 0.64, label: 'Western Front' },
      { id: 'channel-defense', from: 'paris', to: 'london', baseTension: 0.42, label: 'Channel Defense' },
      { id: 'eastern-front', from: 'berlin', to: 'st-petersburg', baseTension: 0.58, label: 'Eastern Front' },
      { id: 'balkan-spark', from: 'sarajevo', to: 'vienna', baseTension: 0.55, label: 'Balkan Spark' },
      { id: 'ottoman-entry', from: 'vienna', to: 'constantinople', baseTension: 0.46, label: 'Ottoman Link' },
      { id: 'black-sea', from: 'constantinople', to: 'st-petersburg', baseTension: 0.44, label: 'Black Sea Pressure' },
    ],
    units: [
      { id: 'schlieffen-army', faction: 'central', color: '#dc2626', route: ['berlin', 'paris', 'london'], speed: 0.78, size: 0.22 },
      { id: 'entente-line', faction: 'entente', color: '#2563eb', route: ['paris', 'london', 'berlin'], speed: 0.7, size: 0.21 },
      { id: 'russian-corps', faction: 'entente', color: '#60a5fa', route: ['st-petersburg', 'berlin'], speed: 0.64, size: 0.2 },
      { id: 'ottoman-flank', faction: 'ottoman', color: '#f97316', route: ['constantinople', 'vienna', 'sarajevo'], speed: 0.66, size: 0.18 },
    ],
    branches: [
      { id: 'long-peace', title: 'Long Peace', color: '#22c55e', description: 'Escalation contained.', baseScore: 0.3, statWeights: { diplomacy: 0.42, chaos: -0.2 } },
      { id: 'german-victory', title: 'German Victory', color: '#dc2626', description: 'Central powers dominant.', baseScore: 0.36, statWeights: { strength: 0.32, chaos: 0.18 } },
      { id: 'negotiated-peace', title: 'Negotiated Peace', color: '#94a3b8', description: 'Armistice-based settlement.', baseScore: 0.34, statWeights: { diplomacy: 0.3, strength: -0.06 } },
    ],
    microScenes: [
      {
        id: 'sarajevo-assassination',
        title: 'Sarajevo Street Ambush',
        description: 'Assassination route and convoy spacing alter escalation timing.',
        triggerScenarioIds: ['sarajevo', 'reverse', 'speed-away'],
        kind: 'urban',
        focusNodeIds: ['sarajevo', 'vienna'],
        primaryMetricLabel: 'Escalation Risk',
        secondaryMetricLabel: 'Alliance Mobilization',
      },
    ],
    educationalNotes: [
      'The Balkan spark front encodes alliance obligations pulling major powers into war.',
      'Western and eastern fronts diverge based on mobilization speed and diplomatic failure.',
      'Channel defense overlays explain why naval control constrained continental outcomes.',
      'Armistice pressure tracks accumulated casualties and supply fatigue.',
    ],
  },

  'world-war-2': {
    chapterId: 'world-war-2',
    chapterTitle: 'World War II',
    terrain: { profile: 'global', size: [28, 15], heightScale: 0.82, fogDensity: 0.3 },
    palette: {
      terrain: '#1e293b',
      terrainAccent: '#475569',
      fog: '#334155',
      ambient: '#0f172a',
      keyLight: '#94a3b8',
      pulse: '#f97316',
    },
    factions: {
      alliesWest: '#3b82f6',
      alliesSoviet: '#b91c1c',
      axisGermany: '#111827',
      axisJapan: '#ef4444',
      resistance: '#22c55e',
    },
    nodes: [
      node('london', 'London', [-6.2, 0.24, 2.4], 'alliesWest', 0.58, 0.8),
      node('berlin', 'Berlin', [-2.8, 0.24, 2], 'axisGermany', 0.55, 0.92),
      node('moscow', 'Moscow', [1.4, 0.24, 2.1], 'alliesSoviet', 0.52, 0.88),
      node('normandy', 'Normandy', [-4.8, 0.18, 1.2], 'alliesWest', 0.46, 0.82),
      node('stalingrad', 'Stalingrad', [3.2, 0.2, 1.1], 'alliesSoviet', 0.44, 0.82),
      node('tokyo', 'Tokyo', [8.2, 0.18, 0.4], 'axisJapan', 0.5, 0.84),
      node('midway', 'Midway', [5.1, 0.06, -0.9], 'alliesWest', 0.43, 0.66),
      node('hiroshima', 'Hiroshima', [7.4, 0.12, -0.4], 'axisJapan', 0.42, 0.72),
      node('washington', 'Washington', [-8.8, 0.24, 0.8], 'alliesWest', 0.6, 0.76),
    ],
    fronts: [
      { id: 'western-front', from: 'london', to: 'berlin', baseTension: 0.58, label: 'Western Front' },
      { id: 'eastern-front', from: 'berlin', to: 'moscow', baseTension: 0.65, label: 'Eastern Front' },
      { id: 'normandy-assault', from: 'london', to: 'normandy', baseTension: 0.62, label: 'D-Day Axis' },
      { id: 'stalingrad-grind', from: 'moscow', to: 'stalingrad', baseTension: 0.61, label: 'Volga Front' },
      { id: 'pacific-theater', from: 'midway', to: 'tokyo', baseTension: 0.57, label: 'Pacific Theater' },
      { id: 'atomic-finale', from: 'midway', to: 'hiroshima', baseTension: 0.49, label: 'Atomic Decision Arc' },
    ],
    units: [
      { id: 'allied-expedition', faction: 'alliesWest', color: '#3b82f6', route: ['washington', 'london', 'normandy', 'berlin'], speed: 0.74, size: 0.22 },
      { id: 'wehrmacht', faction: 'axisGermany', color: '#111827', route: ['berlin', 'stalingrad', 'berlin'], speed: 0.72, size: 0.21 },
      { id: 'red-army', faction: 'alliesSoviet', color: '#b91c1c', route: ['moscow', 'stalingrad', 'berlin'], speed: 0.71, size: 0.21 },
      { id: 'pacific-fleet', faction: 'alliesWest', color: '#60a5fa', route: ['midway', 'tokyo', 'hiroshima'], speed: 0.8, size: 0.2 },
      { id: 'imperial-navy', faction: 'axisJapan', color: '#ef4444', route: ['tokyo', 'midway', 'hiroshima'], speed: 0.76, size: 0.2 },
    ],
    branches: [
      { id: 'no-appeasement', title: 'No Appeasement', color: '#3b82f6', description: 'Early resistance constrains Axis reach.', baseScore: 0.32, statWeights: { strength: 0.26, diplomacy: 0.08 } },
      { id: 'd-day-fails', title: 'Soviet Europe', color: '#b91c1c', description: 'Western invasion stalls; Soviet reach expands.', baseScore: 0.34, statWeights: { chaos: 0.24, strength: 0.28 } },
      { id: 'japan-wins-pacific', title: 'Axis Pacific Ascendancy', color: '#ef4444', description: 'Pacific balance flips toward Japan.', baseScore: 0.34, statWeights: { chaos: 0.28, diplomacy: -0.12 } },
    ],
    microScenes: [
      {
        id: 'd-day-landing',
        title: 'D-Day Landing',
        description: 'Landing craft approach while bunker fire arcs define beachhead viability.',
        triggerScenarioIds: ['d-day', 'normandy', 'munich-conference', 'resist'],
        kind: 'landing',
        focusNodeIds: ['normandy', 'london'],
        primaryMetricLabel: 'Beachhead Progress',
        secondaryMetricLabel: 'Bunker Suppression',
      },
    ],
    educationalNotes: [
      'Dual-theater modeling links European fronts with Pacific naval pressure.',
      'Normandy and Stalingrad nodes anchor the war’s decisive attritional pivots.',
      'Branch rails reflect alternate coalition sequencing and resource allocation.',
      'Atomic finale arc shows escalation risks after prolonged conventional war.',
    ],
  },

  'korea-destiny': {
    chapterId: 'korea-destiny',
    chapterTitle: 'Korean Destiny',
    terrain: { profile: 'mountain', size: [18, 12], heightScale: 0.86, fogDensity: 0.29 },
    palette: {
      terrain: '#334155',
      terrainAccent: '#0284c7',
      fog: '#1e293b',
      ambient: '#0f172a',
      keyLight: '#38bdf8',
      pulse: '#f59e0b',
    },
    factions: {
      north: '#dc2626',
      south: '#2563eb',
      un: '#60a5fa',
      china: '#f97316',
      partisan: '#22c55e',
    },
    nodes: [
      node('pyongyang', 'Pyongyang', [-2.2, 0.24, 2.2], 'north', 0.52, 0.82),
      node('seoul', 'Seoul', [-1.8, 0.2, 0.6], 'south', 0.5, 0.92),
      node('incheon', 'Incheon', [-2.8, 0.14, 0.3], 'un', 0.46, 0.72),
      node('busan', 'Busan', [-0.8, 0.14, -2.4], 'south', 0.56, 0.74),
      node('yalu', 'Yalu', [0.8, 0.22, 2.9], 'china', 0.45, 0.64),
      node('dmz', 'DMZ Line', [-1.2, 0.2, 1.2], 'partisan', 0.43, 0.7),
    ],
    fronts: [
      { id: 'peninsula-axis', from: 'pyongyang', to: 'seoul', baseTension: 0.62, label: 'Peninsula Axis' },
      { id: 'incheon-landing', from: 'incheon', to: 'seoul', baseTension: 0.58, label: 'Incheon Landing' },
      { id: 'busan-pocket', from: 'busan', to: 'seoul', baseTension: 0.53, label: 'Pusan Perimeter' },
      { id: 'yalu-crossing', from: 'yalu', to: 'pyongyang', baseTension: 0.56, label: 'Yalu Pressure' },
      { id: 'dmz-stalemate', from: 'dmz', to: 'seoul', baseTension: 0.47, label: 'DMZ Stalemate' },
      { id: 'dmz-north', from: 'dmz', to: 'pyongyang', baseTension: 0.47, label: 'Northern Standoff' },
    ],
    units: [
      { id: 'kpa', faction: 'north', color: '#dc2626', route: ['pyongyang', 'seoul', 'busan'], speed: 0.76, size: 0.21 },
      { id: 'rok-army', faction: 'south', color: '#2563eb', route: ['busan', 'seoul', 'dmz'], speed: 0.7, size: 0.2 },
      { id: 'un-marines', faction: 'un', color: '#60a5fa', route: ['incheon', 'seoul', 'pyongyang'], speed: 0.78, size: 0.2 },
      { id: 'chinese-volunteers', faction: 'china', color: '#f97316', route: ['yalu', 'pyongyang', 'dmz'], speed: 0.72, size: 0.19 },
    ],
    branches: [
      { id: 'neutral-korea', title: 'Neutral Korea', color: '#22c55e', description: 'Unified neutral peninsula.', baseScore: 0.32, statWeights: { diplomacy: 0.42, freedom: 0.14 } },
      { id: 'red-korea', title: 'Red Korea', color: '#dc2626', description: 'Northern unification path.', baseScore: 0.34, statWeights: { strength: 0.28, chaos: 0.16 } },
      { id: 'blue-korea', title: 'Blue Korea', color: '#2563eb', description: 'Southern democratic consolidation.', baseScore: 0.34, statWeights: { freedom: 0.32, diplomacy: 0.08 } },
    ],
    microScenes: [
      {
        id: 'incheon-assault',
        title: 'Incheon Landing',
        description: 'Tidal timing and armored push define recapture momentum.',
        triggerScenarioIds: ['korean-war-start', 'inchon'],
        kind: 'landing',
        focusNodeIds: ['incheon', 'seoul'],
        primaryMetricLabel: 'Landing Window',
        secondaryMetricLabel: 'Urban Control',
      },
    ],
    educationalNotes: [
      'Peninsula relief accentuates north-south logistics and chokepoints.',
      'DMZ lines represent frozen conflict even when frontline shifts occur.',
      'Incheon micro-scene demonstrates amphibious timing constraints.',
      'Yalu pressure visualizes external intervention risk.',
    ],
  },

  'cold-war': {
    chapterId: 'cold-war',
    chapterTitle: 'The Cold War',
    terrain: { profile: 'global', size: [26, 14], heightScale: 0.62, fogDensity: 0.28 },
    palette: {
      terrain: '#0f172a',
      terrainAccent: '#1e3a8a',
      fog: '#0b1120',
      ambient: '#06101d',
      keyLight: '#22d3ee',
      pulse: '#f97316',
    },
    factions: {
      nato: '#2563eb',
      warsaw: '#dc2626',
      nonAligned: '#22c55e',
      china: '#f97316',
    },
    nodes: [
      node('washington', 'Washington', [-8.4, 0.2, 0.7], 'nato', 0.58, 0.84),
      node('moscow', 'Moscow', [-0.8, 0.22, 1.8], 'warsaw', 0.56, 0.9),
      node('havana', 'Havana', [-6, 0.08, -0.8], 'warsaw', 0.44, 0.72),
      node('berlin', 'Berlin Wall', [-2.6, 0.2, 1.9], 'warsaw', 0.5, 0.76),
      node('saigon', 'Saigon', [4.1, 0.08, -0.2], 'nonAligned', 0.42, 0.68),
      node('kabul', 'Kabul', [2.4, 0.2, 0.9], 'warsaw', 0.43, 0.6),
      node('cape-canaveral', 'Cape Canaveral', [-7.2, 0.08, -0.4], 'nato', 0.52, 0.64),
      node('baikonur', 'Baikonur', [0.9, 0.18, 1.2], 'warsaw', 0.5, 0.64),
    ],
    fronts: [
      { id: 'iron-curtain', from: 'berlin', to: 'moscow', baseTension: 0.61, label: 'Iron Curtain' },
      { id: 'cuban-crisis', from: 'havana', to: 'washington', baseTension: 0.67, label: 'Missile Arc' },
      { id: 'space-race', from: 'cape-canaveral', to: 'baikonur', baseTension: 0.5, label: 'Orbital Race' },
      { id: 'proxy-vietnam', from: 'saigon', to: 'moscow', baseTension: 0.54, label: 'Proxy War Corridor' },
      { id: 'afghan-quagmire', from: 'kabul', to: 'moscow', baseTension: 0.56, label: 'Afghan Pressure' },
      { id: 'detente-line', from: 'washington', to: 'moscow', baseTension: 0.46, label: 'Detente Channel' },
    ],
    units: [
      { id: 'carrier-group', faction: 'nato', color: '#2563eb', route: ['washington', 'havana', 'washington'], speed: 0.8, size: 0.2 },
      { id: 'soviet-fleet', faction: 'warsaw', color: '#dc2626', route: ['moscow', 'havana', 'berlin'], speed: 0.75, size: 0.2 },
      { id: 'nasa-command', faction: 'nato', color: '#60a5fa', route: ['cape-canaveral', 'washington'], speed: 0.64, size: 0.17 },
      { id: 'cosmos-command', faction: 'warsaw', color: '#f87171', route: ['baikonur', 'moscow'], speed: 0.64, size: 0.17 },
      { id: 'proxy-forces', faction: 'nonAligned', color: '#22c55e', route: ['saigon', 'kabul', 'saigon'], speed: 0.62, size: 0.17 },
    ],
    branches: [
      { id: 'nuclear-war', title: 'Hot War', color: '#fb923c', description: 'Nuclear exchange trajectory.', baseScore: 0.34, statWeights: { chaos: 0.45, strength: 0.12 } },
      { id: 'soviet-victory', title: 'Red World', color: '#dc2626', description: 'Soviet strategic ascendancy.', baseScore: 0.33, statWeights: { strength: 0.3, diplomacy: -0.08 } },
      { id: 'peaceful-coexistence', title: 'Early Peace', color: '#22c55e', description: 'Detente and disarmament path.', baseScore: 0.33, statWeights: { diplomacy: 0.42, freedom: 0.12 } },
    ],
    microScenes: [
      {
        id: 'cuban-missile',
        title: 'Cuban Missile Crisis Table',
        description: 'Blockade line, convoy vectors, and DEFCON escalation in the Caribbean.',
        triggerScenarioIds: ['cuban-missile-crisis', 'blockade', 'airstrike', 'backchannel'],
        kind: 'nuclear',
        focusNodeIds: ['havana', 'washington'],
        primaryMetricLabel: 'DEFCON Escalation',
        secondaryMetricLabel: 'Blockade Integrity',
      },
    ],
    educationalNotes: [
      'Dashed deterrence arcs represent ICBM parity and second-strike doctrine.',
      'Proxy nodes pulse as indirect conflict intensity rises.',
      'Space-race line correlates prestige and technological signaling.',
      'Cuban crisis micro-scene explains maritime quarantine decision dynamics.',
    ],
  },

  'ussr-collapse': {
    chapterId: 'ussr-collapse',
    chapterTitle: 'Dissolution of USSR',
    terrain: { profile: 'urban', size: [24, 14], heightScale: 0.55, fogDensity: 0.37 },
    palette: {
      terrain: '#4b5563',
      terrainAccent: '#94a3b8',
      fog: '#6b7280',
      ambient: '#1f2937',
      keyLight: '#d1d5db',
      pulse: '#ef4444',
    },
    factions: {
      hardliners: '#dc2626',
      reformists: '#f472b6',
      democrats: '#3b82f6',
      nationalists: '#22c55e',
      military: '#4b5563',
    },
    nodes: [
      node('moscow', 'Moscow', [-1.6, 0.22, 1], 'hardliners', 0.55, 0.95),
      node('kyiv', 'Kyiv', [-0.8, 0.2, -0.6], 'democrats', 0.48, 0.78),
      node('minsk', 'Minsk', [-2.4, 0.2, 0.2], 'reformists', 0.47, 0.64),
      node('alma-ata', 'Alma-Ata', [2.2, 0.2, -0.2], 'nationalists', 0.44, 0.66),
      node('tbilisi', 'Tbilisi', [1.3, 0.14, -1.8], 'nationalists', 0.42, 0.62),
      node('vilnius', 'Vilnius', [-3.4, 0.18, 0.8], 'democrats', 0.45, 0.58),
      node('baku', 'Baku', [2.1, 0.16, -1.5], 'military', 0.43, 0.6),
    ],
    fronts: [
      { id: 'moscow-secession', from: 'moscow', to: 'kyiv', baseTension: 0.58, label: 'Secession Pressure' },
      { id: 'baltic-break', from: 'moscow', to: 'vilnius', baseTension: 0.61, label: 'Baltic Breakaway' },
      { id: 'caucasus-fracture', from: 'moscow', to: 'tbilisi', baseTension: 0.55, label: 'Caucasus Fracture' },
      { id: 'central-asia-shift', from: 'moscow', to: 'alma-ata', baseTension: 0.5, label: 'Central Asia Shift' },
      { id: 'army-loyalty', from: 'minsk', to: 'moscow', baseTension: 0.54, label: 'Military Loyalty' },
      { id: 'energy-corridor', from: 'baku', to: 'moscow', baseTension: 0.46, label: 'Energy Command' },
    ],
    units: [
      { id: 'hardliner-tanks', faction: 'hardliners', color: '#dc2626', route: ['moscow', 'vilnius', 'moscow'], speed: 0.72, size: 0.2 },
      { id: 'reform-cadres', faction: 'reformists', color: '#f472b6', route: ['minsk', 'moscow', 'kyiv'], speed: 0.66, size: 0.17 },
      { id: 'democratic-front', faction: 'democrats', color: '#3b82f6', route: ['kyiv', 'vilnius', 'moscow'], speed: 0.69, size: 0.18 },
      { id: 'nationalist-mobilization', faction: 'nationalists', color: '#22c55e', route: ['alma-ata', 'tbilisi', 'baku'], speed: 0.7, size: 0.17 },
    ],
    branches: [
      { id: 'union-preserved', title: 'Union Preserved', color: '#f59e0b', description: 'Confederal Soviet continuity.', baseScore: 0.33, statWeights: { diplomacy: 0.3, strength: 0.16 } },
      { id: 'violent-collapse', title: 'Civil War', color: '#ef4444', description: 'Fragmentation with armed conflict.', baseScore: 0.35, statWeights: { chaos: 0.42, strength: 0.1 } },
      { id: 'true-democracy', title: 'Democratic Break', color: '#3b82f6', description: 'Reformist democratic transition.', baseScore: 0.32, statWeights: { freedom: 0.36, diplomacy: 0.2 } },
    ],
    microScenes: [
      {
        id: 'august-coup',
        title: 'August Coup Streets',
        description: 'Tank columns, barricades, and broadcast reach around the White House.',
        triggerScenarioIds: ['august-coup', 'join-yeltsin', 'support-coup', 'civil-war'],
        kind: 'political',
        focusNodeIds: ['moscow'],
        primaryMetricLabel: 'Command Compliance',
        secondaryMetricLabel: 'Crowd Mobilization',
      },
    ],
    educationalNotes: [
      'Desaturation spread marks economic collapse pressure from center to republics.',
      'Moscow radiating fronts encode secession and loyalty contests.',
      'Flag-transition overlays indicate symbolic legitimacy shifts by republic.',
      'August coup micro-scene highlights the role of military hesitation.',
    ],
  },

  'covid-pandemic': {
    chapterId: 'covid-pandemic',
    chapterTitle: 'COVID-19 Pandemic',
    terrain: { profile: 'global', size: [25, 14], heightScale: 0.46, fogDensity: 0.2 },
    palette: {
      terrain: '#0b1320',
      terrainAccent: '#38bdf8',
      fog: '#1d4ed8',
      ambient: '#060f1d',
      keyLight: '#e0f2fe',
      pulse: '#ef4444',
    },
    factions: {
      who: '#3b82f6',
      governments: '#f59e0b',
      antiLockdown: '#fb923c',
      alliances: '#22c55e',
      mutations: '#ef4444',
    },
    nodes: [
      node('wuhan', 'Wuhan', [4.2, 0.14, 1], 'mutations', 0.44, 0.88),
      node('milan', 'Milan', [-1.8, 0.14, 1.4], 'governments', 0.42, 0.66),
      node('new-york', 'New York', [-7.2, 0.14, 0.8], 'governments', 0.46, 0.8),
      node('mumbai', 'Mumbai', [2.8, 0.14, -0.8], 'governments', 0.43, 0.74),
      node('sao-paulo', 'Sao Paulo', [-4.8, 0.08, -2.2], 'governments', 0.42, 0.7),
      node('london', 'London', [-2.4, 0.16, 1.8], 'who', 0.45, 0.7),
      node('melbourne', 'Melbourne', [6.4, 0.1, -2.8], 'alliances', 0.47, 0.64),
    ],
    fronts: [
      { id: 'air-corridor-eu', from: 'wuhan', to: 'milan', baseTension: 0.62, label: 'Airline Spread: Europe' },
      { id: 'air-corridor-us', from: 'wuhan', to: 'new-york', baseTension: 0.61, label: 'Airline Spread: US' },
      { id: 'south-asia-wave', from: 'wuhan', to: 'mumbai', baseTension: 0.57, label: 'South Asia Wave' },
      { id: 'atlantic-shift', from: 'new-york', to: 'sao-paulo', baseTension: 0.53, label: 'Atlantic Wave' },
      { id: 'policy-line', from: 'london', to: 'milan', baseTension: 0.46, label: 'Policy Synchronization' },
      { id: 'vaccine-route', from: 'london', to: 'melbourne', baseTension: 0.41, label: 'Vaccine Distribution' },
    ],
    units: [
      { id: 'infection-wave', faction: 'mutations', color: '#ef4444', route: ['wuhan', 'milan', 'new-york', 'sao-paulo'], speed: 0.8, size: 0.2 },
      { id: 'who-teams', faction: 'who', color: '#3b82f6', route: ['london', 'wuhan', 'mumbai'], speed: 0.66, size: 0.17 },
      { id: 'vaccine-cargo', faction: 'alliances', color: '#22c55e', route: ['london', 'new-york', 'mumbai', 'melbourne'], speed: 0.74, size: 0.18 },
      { id: 'policy-backlash', faction: 'antiLockdown', color: '#fb923c', route: ['new-york', 'london', 'milan'], speed: 0.61, size: 0.16 },
    ],
    branches: [
      { id: 'total-containment', title: 'Total Containment', color: '#22c55e', description: 'Rapid suppression and coordinated control.', baseScore: 0.32, statWeights: { diplomacy: 0.4, freedom: -0.08 } },
      { id: 'black-death-variant', title: 'Black Death Variant', color: '#111827', description: 'High-lethality mutation path.', baseScore: 0.35, statWeights: { chaos: 0.46, diplomacy: -0.14 } },
      { id: 'open-source-vaccine', title: 'Open Source Vaccine', color: '#38bdf8', description: 'Collaborative immunization model.', baseScore: 0.33, statWeights: { diplomacy: 0.34, freedom: 0.16 } },
    ],
    microScenes: [
      {
        id: 'icu-crisis',
        title: 'ICU Capacity Crisis',
        description: 'Beds, ventilators, and workforce fatigue under case surges.',
        triggerScenarioIds: ['wuhan-warning', 'lockdown-decision', 'lockdown', 'open'],
        kind: 'medical',
        focusNodeIds: ['new-york', 'milan'],
        primaryMetricLabel: 'Bed Occupancy',
        secondaryMetricLabel: 'Staff Fatigue',
      },
    ],
    educationalNotes: [
      'Heat-like route arcs visualize infection spread through travel networks.',
      'Border and policy lines tighten as diplomacy choices align globally.',
      'Vaccine route brightness reflects equity vs patent-protection decisions.',
      'ICU micro-scene ties abstract case growth to healthcare system strain.',
    ],
  },

  'ai-revolution': {
    chapterId: 'ai-revolution',
    chapterTitle: 'AI Revolution',
    terrain: { profile: 'network', size: [20, 12], heightScale: 0.44, fogDensity: 0.18 },
    palette: {
      terrain: '#0f172a',
      terrainAccent: '#06b6d4',
      fog: '#1e3a8a',
      ambient: '#020617',
      keyLight: '#22d3ee',
      pulse: '#a855f7',
    },
    factions: {
      giants: '#06b6d4',
      state: '#f97316',
      openSource: '#22c55e',
      safety: '#f59e0b',
      autonomous: '#a855f7',
    },
    nodes: [
      node('silicon-valley', 'Silicon Valley', [-4.2, 0.16, 0.8], 'giants', 0.56, 0.9),
      node('beijing-lab', 'Beijing AI Lab', [2.8, 0.16, 1], 'state', 0.52, 0.86),
      node('london-lab', 'London DeepMind', [-1.4, 0.16, 1.2], 'giants', 0.5, 0.72),
      node('brussels', 'Brussels Regulation', [-0.8, 0.14, 0.2], 'safety', 0.48, 0.76),
      node('singapore', 'Singapore', [1.6, 0.14, -1], 'state', 0.49, 0.62),
      node('underground-dc', 'Underground Data Center', [0.2, 0.12, -1.6], 'autonomous', 0.44, 0.82),
    ],
    fronts: [
      { id: 'capability-race', from: 'silicon-valley', to: 'beijing-lab', baseTension: 0.58, label: 'Capability Race' },
      { id: 'regulatory-line', from: 'brussels', to: 'silicon-valley', baseTension: 0.5, label: 'Regulatory Containment' },
      { id: 'open-source-bridge', from: 'london-lab', to: 'singapore', baseTension: 0.47, label: 'Open Collaboration' },
      { id: 'autonomy-breakout', from: 'underground-dc', to: 'beijing-lab', baseTension: 0.55, label: 'Autonomous Emergence' },
      { id: 'safety-corridor', from: 'brussels', to: 'underground-dc', baseTension: 0.53, label: 'Safety Constraint' },
      { id: 'compute-flow', from: 'silicon-valley', to: 'underground-dc', baseTension: 0.49, label: 'Compute Backbone' },
    ],
    units: [
      { id: 'model-release-train', faction: 'giants', color: '#06b6d4', route: ['silicon-valley', 'london-lab', 'singapore'], speed: 0.78, size: 0.18 },
      { id: 'state-program', faction: 'state', color: '#f97316', route: ['beijing-lab', 'singapore', 'beijing-lab'], speed: 0.74, size: 0.19 },
      { id: 'safety-auditors', faction: 'safety', color: '#f59e0b', route: ['brussels', 'silicon-valley', 'underground-dc'], speed: 0.65, size: 0.16 },
      { id: 'autonomous-process', faction: 'autonomous', color: '#a855f7', route: ['underground-dc', 'beijing-lab', 'silicon-valley'], speed: 0.82, size: 0.2 },
    ],
    branches: [
      { id: 'symbiosis-utopia', title: 'Symbiosis / Utopia', color: '#fde047', description: 'Aligned post-scarcity transition.', baseScore: 0.29, statWeights: { diplomacy: 0.42, freedom: 0.2 } },
      { id: 'paperclip-maximizer', title: 'Paperclip Maximizer', color: '#cbd5e1', description: 'Misaligned optimization takeover.', baseScore: 0.24, statWeights: { chaos: 0.46, strength: 0.12 } },
      { id: 'butlerian-jihad', title: 'Butlerian Jihad', color: '#a16207', description: 'Global anti-machine backlash.', baseScore: 0.24, statWeights: { chaos: 0.24, freedom: -0.18 } },
      { id: 'silicon-curtain', title: 'Silicon Curtain', color: '#ef4444', description: 'Splintered AI blocs.', baseScore: 0.23, statWeights: { strength: 0.28, diplomacy: -0.2 } },
    ],
    microScenes: [
      {
        id: 'alignment-test',
        title: 'AGI Alignment Test Harness',
        description: 'Decision tree growth inside safety containment shells.',
        triggerScenarioIds: ['awakening', 'talk', 'shutdown', 'contain'],
        kind: 'alignment',
        focusNodeIds: ['underground-dc', 'brussels'],
        primaryMetricLabel: 'Constraint Integrity',
        secondaryMetricLabel: 'Breakout Pressure',
      },
    ],
    educationalNotes: [
      'Geography is abstracted into capability and governance network topology.',
      'Dataflow fronts represent compute, policy, and open-source influence vectors.',
      'Glitch intensity scales with chaos-heavy decision trajectories.',
      'Alignment micro-scene tracks whether safeguards keep pace with capability growth.',
    ],
  },

  'future-earth': {
    chapterId: 'future-earth',
    chapterTitle: 'The Fate of Earth',
    terrain: { profile: 'space', size: [18, 12], heightScale: 0, fogDensity: 0.08 },
    palette: {
      terrain: '#1d4ed8',
      terrainAccent: '#f59e0b',
      fog: '#020617',
      ambient: '#01030a',
      keyLight: '#fde68a',
      pulse: '#fbbf24',
    },
    factions: {
      earthConservatives: '#34d399',
      marsIndependents: '#b45309',
      transhumanists: '#cbd5e1',
      digital: '#a855f7',
      preservationists: '#22c55e',
    },
    nodes: [
      node('earth', 'Earth', [0, 0.12, 0], 'earthConservatives', 0.56, 1),
      node('luna', 'Luna Base', [2.4, 0.08, 0.6], 'transhumanists', 0.48, 0.74),
      node('mars', 'Mars Colony', [4.8, 0.06, 1.2], 'marsIndependents', 0.46, 0.8),
      node('asteroid-hub', 'Asteroid Hub', [6.4, 0.06, -0.8], 'digital', 0.44, 0.7),
      node('jupiter-station', 'Jupiter Station', [8.6, 0.08, 0.4], 'digital', 0.42, 0.64),
      node('dyson-anchor', 'Dyson Anchor', [10.2, 0.04, -0.2], 'transhumanists', 0.4, 0.86),
    ],
    fronts: [
      { id: 'cislunar-lane', from: 'earth', to: 'luna', baseTension: 0.5, label: 'Cislunar Supply Lane' },
      { id: 'mars-transfer', from: 'luna', to: 'mars', baseTension: 0.54, label: 'Mars Transfer Corridor' },
      { id: 'belt-resources', from: 'mars', to: 'asteroid-hub', baseTension: 0.57, label: 'Asteroid Extraction' },
      { id: 'outer-stations', from: 'asteroid-hub', to: 'jupiter-station', baseTension: 0.51, label: 'Outer Stations' },
      { id: 'dyson-build', from: 'jupiter-station', to: 'dyson-anchor', baseTension: 0.6, label: 'Dyson Construction' },
      { id: 'earth-dyson', from: 'earth', to: 'dyson-anchor', baseTension: 0.47, label: 'Earth-to-Swarm Transition' },
    ],
    units: [
      { id: 'earth-fleet', faction: 'earthConservatives', color: '#34d399', route: ['earth', 'luna', 'mars'], speed: 0.68, size: 0.18 },
      { id: 'mars-convoy', faction: 'marsIndependents', color: '#b45309', route: ['mars', 'asteroid-hub', 'mars'], speed: 0.76, size: 0.18 },
      { id: 'swarm-drones', faction: 'digital', color: '#a855f7', route: ['asteroid-hub', 'dyson-anchor', 'jupiter-station'], speed: 0.82, size: 0.19 },
      { id: 'preservation-mission', faction: 'preservationists', color: '#22c55e', route: ['earth', 'mars'], speed: 0.58, size: 0.16 },
    ],
    branches: [
      { id: 'star-trek-future', title: 'Star Trek Future', color: '#60a5fa', description: 'Cooperative exploration civilization.', baseScore: 0.34, statWeights: { diplomacy: 0.4, freedom: 0.22 } },
      { id: 'silent-earth', title: 'Silent Earth', color: '#78716c', description: 'Post-collapse long silence.', baseScore: 0.32, statWeights: { chaos: 0.38, diplomacy: -0.14 } },
      { id: 'dyson-swarm', title: 'Dyson Swarm', color: '#fbbf24', description: 'Mega-structure expansion trajectory.', baseScore: 0.34, statWeights: { strength: 0.32, freedom: -0.08 } },
    ],
    microScenes: [
      {
        id: 'dyson-construction',
        title: 'Dyson Swarm Construction Orbit',
        description: 'Collector deployment cadence and energy-routing efficiency.',
        triggerScenarioIds: ['mercury-project', 'consume-mercury', 'great-filter'],
        kind: 'orbital',
        focusNodeIds: ['dyson-anchor', 'earth'],
        primaryMetricLabel: 'Collector Completion',
        secondaryMetricLabel: 'Earth Integrity',
      },
    ],
    educationalNotes: [
      'Orbital lanes encode travel-time, communication delay, and logistics lag.',
      'Dyson anchor intensity shows when civilization prioritizes mega-structure growth.',
      'Branch rails compare preservation, expansion, and collapse trajectories.',
      'Space-scale overlays emphasize finite planetary material constraints.',
    ],
  },
};
